### ISSUE TITLE
Publish daybed.js on spiral-project.github.io/daybed.js

### ISSUE THREAD

**Issue by almet** [spiral-project/daybed.js#20]
It could be very useful to have the minified `daybed.js` file available somewhere in the repo and published as well on github pages.

**Comment by leplatrem** [comment]
I saw that you installed the tools for gulp... Maybe you should just setup Travis to push it [this way](http://blog.mathieu-leplatre.info/publish-your-pelican-blog-on-github-pages-via-travis-ci.html) 

Otherwise NPM for official versions and https://rawgit.com for others seems fine enough to me :)

**Comment by leplatrem** [comment]
Would be nice to have now that examples were merged :)

**Comment by almet** [comment]
yeah, and that will help us to have it released without any troubles for us.

**Comment by leplatrem** [comment]
Done ! http://spiral-project.github.io/daybed.js/build/daybed.js
