### ISSUE TITLE
Use Promises for requests

### ISSUE THREAD

**Issue by leplatrem** [spiral-project/daybed.js#3]
Example of implementation : https://github.com/tyabonil/request-promise/blob/master/lib/rp.js

Usage is then much clearer using '.then()' and '.catch()'

**Comment by Natim** [comment]
Matter of taste :dart:

**Comment by Natim** [comment]
Also how do you use require in a web environment?

**Comment by leplatrem** [comment]
With http://browserify.org

**Comment by Natim** [comment]
Great: http://superbigtree.tumblr.com/post/54873453939/introduction-to-browserify

**Comment by leplatrem** [comment]
I would suggest you don't add a dependency on this "request-promise" module, but implement Promises within daybed.js, since the amount of code is very small

**Comment by Natim** [comment]
I am not a fan of promise anyway.

**Comment by Natim** [comment]
Also it makes sense for the HighAPI

**Comment by Natim** [comment]
It doesn't seems to me to be a small amount of code https://github.com/petkaantonov/bluebird

**Comment by leplatrem** [comment]
If, like Q or bluebird, you reimplement the Promise stack from scratch, of course it's a lot of code ! 
But, by now we can use the young standard http://caniuse.com/#search=promise

**Comment by Natim** [comment]
ok then

**Comment by leplatrem** [comment]
I can take this if you are not in a hurry :)

**Comment by leplatrem** [comment]
Well actually, the code is here already : http://www.html5rocks.com/en/tutorials/es6/promises/#toc-promisifying-xmlhttprequest

**Comment by Natim** [comment]
Ok great je m'en occupe

**Comment by Natim** [comment]
See #4

**Comment by leplatrem** [comment]
-> moved comment to PR
